### ISSUE TITLE
Update on Release

### ISSUE THREAD

**Issue by theperfectwill** [hexydec/agentzero#1]
@hexydec Hi!

Would you mind commenting back when this is out of BETA?

I found myself in search to replace an old User Agent repo, and was regoing through the tokeniser and its minifiers, and saw your new repo. So when it's ready you feel, I can give it some implementation and tests as well.

If that's cool with you? :)

**Comment by hexydec** [comment]
It's pretty much ready for testing into production now. It has a full test suite of around 370 tests.

I do need to do another release though, so if you are going to test it, clone the head commit.

You can try it on my portfolio too: https://hexydec.com/apps/user-agent-parser/

**Comment by hexydec** [comment]
Were you using`get_browser()`? This should give you much more granular info, and categories for robots too.
