### ISSUE TITLE
Yandex browser detections

### ISSUE THREAD

**Issue by ivankuraev** [hexydec/agentzero#2]
Hello.

Can you improve detection support of Yandex browsers?

YaApp_Android = Yandex Start
YaSearchBrowser = Yandex Alice
YaBrowser = Yandex

Thanky you.

**Comment by hexydec** [comment]
Had a think about this issue, and whilst generalising the app name is useful to normalise and group the data, the original app name should probably not be lost.

I am going to introduce a new property that will return the original app name, and tighten up the normalising it a bit to make it slightly more general.

Lookout for a new release soon with this update.

**Comment by ivankuraev** [comment]
Great.
Based on original app name I can use custom browser names in project. Thank you.
