### ISSUE TITLE
Missing detection of Huawei Browser

### ISSUE THREAD

**Issue by ivankuraev** [hexydec/agentzero#5]
Hello.

Android mobile Huawei Browser is not detected.

UserAgent examples:

Mozilla/5.0 (Linux; Android 12; GLA-LX1; HMSCore 6.12.0.302) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 HuaweiBrowser/14.0.0.322 Mobile Safari/537.36

Mozilla/5.0 (Linux; Android 10; EVE-LX9N; HMSCore 6.11.4.312) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 HuaweiBrowser/14.0.0.322 Mobile Safari/537.36

Mozilla/5.0 (Linux; Android 10; MED-LX9N; HMSCore 6.12.2.301) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 HuaweiBrowser/14.0.2.311 Mobile Safari/537.36

**Comment by hexydec** [comment]
Thanks for letting me know and providing strings. Have added detection and tests. Will be in the next release.
